### ISSUE TITLE
Error with `cluster_screens`

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/FormFyxer#133]
```
formfyxer.cluster_screens(["variable1", "variable2"], tools_token="b02e7ccf464b49d09e6a09359846e535abc7416ed90e49f5bcd56d9ebbcaf9e4")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/quinten/FormFyxer/formfyxer/lit_explorer.py", line 469, in cluster_screens
    vec_mat[i] = vecs[i]
IndexError: list index out of range
```

**Comment by nonprofittechy** [comment]
ah, I think it's just a DOCX file without any fields. probably some additional error handling we should add here
