### ISSUE TITLE
Error with newly installed package

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/FormFyxer#18]
This is a different one, sorry. I hadn't run into this because it's already downloaded on the Dev server. It's not installed on the Test server yet.

```
    OSError: [E050] Can't find model 'en_core_web_lg'. It doesn't seem to be a Python package or a valid path to a data directory.

Log

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/formfyxer/lit_explorer.py", line 35, in <module>
    nlp = spacy.load('en_core_web_lg') # this takes a while to loadimport os
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/spacy/__init__.py", line 51, in load
    return util.load_model(
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/spacy/util.py", line 427, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_lg'. It doesn't seem to be a Python package or a valid path to a data directory.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/webapp/server.py", line 7510, in index
    interview.assemble(user_dict, interview_status, old_user_dict, force_question=special_question)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 7555, in assemble
    exec('import ' + module_name, user_dict)
  File "<string>", line 1, in <module>
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/formfyxer/__init__.py", line 1, in <module>
    from .lit_explorer import *
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/formfyxer/lit_explorer.py", line 42, in <module>
    nlp = spacy.load('en_core_web_lg') # this takes a while to loadimport os
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/spacy/__init__.py", line 51, in load
    return util.load_model(
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/spacy/util.py", line 427, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_lg'. It doesn't seem to be a Python package or a valid path to a data directory.
```

**Comment by colarusso** [comment]
Hum.. this was made to take care of that, but perhaps there's a problem with the bash command. 

```
try:
    nlp = spacy.load('en_core_web_lg') # this takes a while to loadimport os
except:
    print("Downloading word2vec model en_core_web_lg")
    import subprocess
    bashCommand = "python -m spacy download en_core_web_lg"
    process = subprocess.Popen(bashCommand.split(), stdout=subprocess.PIPE)
    output, error = process.communicate()
    nlp = spacy.load('en_core_web_lg') # this takes a while to loadimport os
```

**Comment by BryceStevenWilley** [comment]
Confirmed on a blank docassemble server that installing the FormFyxer package doesn't crash the server.
