### ISSUE TITLE
Error importing in Docassemble

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/FormFyxer#8]
After installing with `pip`, adding `imports: formfyxer` to a Docassemble interview results in this error:

```
LookupError: 
**********************************************************************
  Resource [93mstopwords[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('stopwords')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/stopwords[0m

  Searched in:
    - '/var/www/nltk_data'
    - '/usr/share/docassemble/local3.8/nltk_data'
    - '/usr/share/docassemble/local3.8/share/nltk_data'
    - '/usr/share/docassemble/local3.8/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

Log

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93mstopwords[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('stopwords')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/stopwords.zip/stopwords/[0m

  Searched in:
    - '/var/www/nltk_data'
    - '/usr/share/docassemble/local3.8/nltk_data'
    - '/usr/share/docassemble/local3.8/share/nltk_data'
    - '/usr/share/docassemble/local3.8/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/webapp/server.py", line 7555, in index
    interview.assemble(user_dict, interview_status, old_user_dict, force_question=special_question)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 7589, in assemble
    exec('import ' + module_name, user_dict)
  File "<string>", line 1, in <module>
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/formfyxer/__init__.py", line 1, in <module>
    from .lit_explorer import *
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/formfyxer/lit_explorer.py", line 30, in <module>
    stop_words = set(stopwords.words('english'))
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93mstopwords[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('stopwords')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/stopwords[0m

  Searched in:
    - '/var/www/nltk_data'
    - '/usr/share/docassemble/local3.8/nltk_data'
    - '/usr/share/docassemble/local3.8/share/nltk_data'
    - '/usr/share/docassemble/local3.8/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
```

**Comment by nonprofittechy** [comment]
It looks like this might be a one-time setup task, but we should make this work out of the box for new installs

**Comment by nonprofittechy** [comment]
@colarusso this is still an issue as of the latest (24dcf984297674b55d2643e2bd57878208e32604)

**Comment by colarusso** [comment]
Same error I presume?

**Comment by nonprofittechy** [comment]
yes, same error.

**Comment by colarusso** [comment]
I think @BryceStevenWilley's recent PR should have fixed this. I've made the change to the notebook too so it won't be overwritten, incremented the build number, and redeployed.
