### ISSUE TITLE
At least one parameter to `parse_form` is not actually None safe

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/FormFyxer#9]
```
Traceback (most recent call last):
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/webapp/server.py", line 7555, in index
    interview.assemble(user_dict, interview_status, old_user_dict, force_question=special_question)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 8032, in assemble
    raise the_error
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 7821, in assemble
    question_result = self.askfor(missingVariable, user_dict, old_user_dict, interview_status, seeking=interview_status.seeking, follow_mc=follow_mc, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 8480, in askfor
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 9086, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "<code block>", line 1, in <module>
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/formfyxer/lit_explorer.py", line 401, in parse_form
    title = reCase(re.search("(.*)\n",text).group(1).strip())
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by nonprofittechy** [comment]
More specifically--looks like issue is when `re.search()` has no matches

**Comment by nonprofittechy** [comment]
Fixed in the notebook
